docs: Fix docker build uid issue. Move docs related make commands into docs dir. Move docs tasks into docs/Makefile.
Locally I was getting the error because of undefined UID var. I've fixed
it alinging the solution with how docs organized in VictoriaMetrics
repo.

```
3.531 OK: 33 MiB in 44 packages
5.535 adduser: uid '0' in use
------
Dockerfile:14
--------------------
  13 |
  14 | >>> RUN \
  15 | >>>   apk add \
  16 | >>>     curl \
  17 | >>>     jq \
  18 | >>>     libstdc++ \
  19 | >>>     libwebp-tools \
  20 | >>>     gcompat && \
21 | >>>   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
  22 | >>>     icu-libs && \
23 | >>>   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
  24 | >>>     dart-sass && \
  25 | >>>   curl \
  26 | >>>     -fsSL ${HUGO_URL} \
  27 | >>>     --output hugo.tar.gz && \
  28 | >>>   tar -xzf hugo.tar.gz && \
  29 | >>>   mv hugo /usr/bin/ && \
  30 | >>>   mkdir /opt/docs && \
  31 | >>>   deluser node && \
  32 | >>>   adduser -u ${UID} -D hugo
  33 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add     curl     jq
libstdc++     libwebp-tools     gcompat &&   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/main/
icu-libs &&   apk add
--repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
dart-sass &&   curl     -fsSL ${HUGO_URL}     --output hugo.tar.gz &&
tar -xzf hugo.tar.gz &&   mv hugo /usr/bin/ &&   mkdir /opt/docs &&
deluser node &&   adduser -u ${UID} -D hugo" did not complete
successfully: exit code: 1
```